services:
    fondofakeneo_export_connector.job.job_parameters.default_values_provider.simple_csv_export:
         class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleCsvExport'
         arguments:
             - '@akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_csv_export'
             - '@pim_catalog.repository.channel'
             - '@pim_catalog.repository.locale'
             -
                 - '%fondofakeneo_export_connector.job_name.csv_product_export%'
         tags:
             - { name: akeneo_batch.job.job_parameters.default_values_provider }

    fondofakeneo_export_connector.job.job_parameters.constraint_collection_provider.product_csv_export:
        class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleCsvExport'
        arguments:
            - '@akeneo_pim_structure.job.job_parameters.constraint_collection_provider.simple_csv_export'
            -
                - '%fondofakeneo_export_connector.job_name.csv_product_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
