services:
  fondofakeneo_export_connector.provider.form.job_instance:
      class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
      arguments:
          -
            fondofakeneo_csv_product_export: pim-job-instance-csv-product-export
      tags:
          - { name: pim_enrich.provider.form }